# Generated by Django 5.2.16 on 2026-07-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaInformativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título de la Tarjeta')),
                ('descripcion', models.TextField(verbose_name='Descripción breve')),
                ('imagen', models.ImageField(upload_to='tarjetas/', verbose_name='Imagen representativa')),
                ('enlace', models.URLField(blank=True, null=True, verbose_name='Enlace (Opcional)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Mostrar en el portal?')),
            ],
            options={
                'verbose_name': 'Tarjeta Informativa',
                'verbose_name_plural': 'Tarjetas Informativas',
                'ordering': ['orden', '-id'],
            },
        ),
    ]
