# Generated by Django 5.2.16 on 2026-07-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarruselHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, verbose_name='Título principal')),
                ('subtitulo', models.CharField(blank=True, max_length=250, verbose_name='Subtítulo')),
                ('imagen', models.ImageField(upload_to='carrusel/', verbose_name='Imagen de fondo')),
                ('texto_boton', models.CharField(blank=True, default='Saber más', max_length=50)),
                ('enlace_boton', models.URLField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Imagen de Carrusel',
                'verbose_name_plural': 'Carrusel Principal',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='tarjetainformativa',
            options={'ordering': ['orden', '-id']},
        ),
        migrations.AlterField(
            model_name='tarjetainformativa',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tarjetainformativa',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tarjetainformativa',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarjetainformativa',
            name='imagen',
            field=models.ImageField(upload_to='tarjetas/'),
        ),
        migrations.AlterField(
            model_name='tarjetainformativa',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tarjetainformativa',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
