# Generated by Django 5.2.16 on 2026-07-29 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carruselhero_alter_tarjetainformativa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carruselhero',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='carruselhero',
            name='video_fondo',
            field=models.FileField(blank=True, null=True, upload_to='carrusel_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='carruselhero',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='carrusel/'),
        ),
        migrations.AlterField(
            model_name='carruselhero',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='carruselhero',
            name='titulo',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
