# Generated by Django 5.2.16 on 2026-07-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_carruselhero_options_carruselhero_video_fondo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración Principal', max_length=100)),
                ('fondo_seccion', models.ImageField(blank=True, help_text='Imagen de fondo para la sección media del portal', null=True, upload_to='configuracion/')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuraciones del Sitio',
            },
        ),
        migrations.AlterModelOptions(
            name='carruselhero',
            options={'ordering': ['orden'], 'verbose_name': 'Slide Carrusel', 'verbose_name_plural': 'Slides Carrusel'},
        ),
        migrations.AlterModelOptions(
            name='tarjetainformativa',
            options={'ordering': ['orden', '-id'], 'verbose_name': 'Tarjeta Informativa', 'verbose_name_plural': 'Tarjetas Informativas'},
        ),
    ]
