# Generated by Django 5.2.16 on 2026-07-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_configuracionsitio_alter_carruselhero_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nuestro Campus', max_length=150)),
                ('descripcion', models.TextField()),
                ('imagen_fondo', models.ImageField(upload_to='campus/')),
                ('enlace_video', models.URLField(blank=True, help_text='Enlace institucional opcional', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('destacada', models.BooleanField(default=False, help_text='Las imágenes destacadas ocupan el doble de espacio en el mosaico visual.')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOTICIA', 'Noticia'), ('EVENTO', 'Evento')], default='NOTICIA', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField(max_length=500)),
                ('imagen', models.ImageField(upload_to='noticias/')),
                ('fecha', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SeccionDoble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('subtitulo', models.CharField(blank=True, max_length=250)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='secciones_dobles/')),
                ('alineacion_imagen_derecha', models.BooleanField(default=True, help_text='Si se marca, la imagen irá a la derecha y el texto a la izquierda. Si no, al revés.')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_aspirante', models.CharField(max_length=150)),
                ('apellido_aspirante', models.CharField(max_length=150)),
                ('grado_postulacion', models.CharField(max_length=50)),
                ('nombre_acudiente', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('mensaje', models.TextField(blank=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracionSitio',
        ),
        migrations.AlterModelOptions(
            name='carruselhero',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='tarjetainformativa',
            options={'ordering': ['orden', '-id']},
        ),
    ]
