# Generated by Django 5.2.16 on 2026-07-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_campusseccion_galeriaitem_noticiaevento_secciondoble_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carruselhero',
            options={'ordering': ['orden'], 'verbose_name': 'Slide Carrusel', 'verbose_name_plural': 'Slides Carrusel'},
        ),
        migrations.RemoveField(
            model_name='galeriaitem',
            name='destacada',
        ),
        migrations.AlterField(
            model_name='campusseccion',
            name='enlace_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galeriaitem',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='secciondoble',
            name='alineacion_imagen_derecha',
            field=models.BooleanField(default=True),
        ),
    ]
